version: '2'

services:

  ros2-dashing:
    build: ./docker/ros2_dashing
    container_name: "ros2-dashing"
    volumes:
      - ./app:/home/ubuntu/app
    expose:
      - "80"
      - "6080"
      - "11311"
    ports:
      - "6080:80"
      - "11311:11311"
    environment:
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
      - TURTLEBOT3_MODEL=burger
