version: '2'

services:

  ros2-dashing:
    build: ./docker/ros2_dashing
    container_name: "ros2-dashing"
    volumes:
      - ./app:/home/ubuntu/app
    network_mode: 'host'
    environment:
      - TURTLEBOT3_MODEL=burger
    entrypoint: /bin/bash
    command: -c "/home/ubuntu/app/startup.sh"
